#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

#case $BLOCK_BUTTON in
#	3) notify-send "🔋 Battery module" "🔋: discharging
#🛑: not charging
#♻: stagnant charge
#🔌: charging
#⚡: charged
#❗: battery very low!
#- Scroll to change adjust xbacklight." ;;
#	4) xbacklight -inc 10 ;;
#	5) xbacklight -dec 10 ;;
#	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

# Loop through all attached batteries and format the info

notify() {
    notify-send \
        --icon=battery-good-symbolic \
        --expire-time=4000 \
        --hint=string:x-canonical-private-synchronous:battery \
        "Battery" "$1"
}

brctl() {
  set -- "$1"
  cmd="$1"
  arg="$2"


  # brightnessctl s $arg
  
  if [ "$cmd" = "inc" ]; then
    brightnessctl s 20+
  elif [ "$cmd" = "dec" ]; then
    cur=`brightnessctl g`
    if [ $cur -ge 100 ]; then
      brightnessctl s 20-
    fi
  fi
}

case "$BLOCK_BUTTON" in
  1) rofi_battery ;;
  4) brctl "inc" ;;
  5) brctl "dec" ;;
esac

#case "$BLOCK_BUTTON" in
#    1) notify "$(acpi -b | awk -F ': |, ' '{printf "%s\n%s\n", $2, $4}')" ;;
#    6) terminal -e "$EDITOR" "$0" ;;
#esac


. sb-theme

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "

    capacity="$(cat "$battery/capacity" 2>&1)"
    if [ "$capacity" -gt 90 ]; then
        status="󰁹 "
	color=2
    elif [ "$capacity" -gt 60 ]; then
        status="󰁿 "
	color=4
    elif [ "$capacity" -gt 40 ]; then
        status="󰁼 "
	color=15
    elif [ "$capacity" -gt 10 ]; then
        status="󰁺 "
	color=9
    else
        status="󱃍 "
	color=9
    fi

    case "$(cat "$battery/status" 2>&1)" in
        Full) 
	   status="⚡️ " 
	;;
        Discharging)
            if [ "$capacity" -le 20 ]; then
                status="$status"
            fi
            ;;
        Charging) status=" $status" ;;
        "Not charging") status="  " ;;
        Unknown) status="? $status" ;;
        *) exit 1 ;;
    esac

    display "$status$capacity%" "$color"
done
