#!/usr/bin/env sh
#
# Saumon i3blocks scripts
# temperature (hardware temperature)
#

if ! command -v sensors >/dev/null; then
  TEMP="?"
else
  TEMP=$(sensors -u | grep -m1 temp1_input | awk '{printf ("%d",$2)}')
fi



if [ "$TEMP" = "?" ]; then
  ICON="🌡️"
  color=15
elif [ "$TEMP" -ge 75 ]; then
  ICON="🔥"
  color=11
elif [ "$TEMP" -ge 55 ]; then
  ICON="🌡️"
  color=12
else
  ICON="🧊"
  color=15
fi

. sb-theme
display "$ICON $TEMP °C" $color

